# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(750, 842)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(280, 10, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: italic 18pt \"Ubuntu\";\n"
"font: italic 24pt \"Ubuntu\";")
        self.label.setObjectName("label")
        self.tabPrincipal = QtWidgets.QTabWidget(Dialog)
        self.tabPrincipal.setGeometry(QtCore.QRect(0, 60, 751, 771))
        self.tabPrincipal.setObjectName("tabPrincipal")
        self.tabCrudFarmacias = QtWidgets.QWidget()
        self.tabCrudFarmacias.setObjectName("tabCrudFarmacias")
        self.tb_agregarFarmacia = QtWidgets.QTabWidget(self.tabCrudFarmacias)
        self.tb_agregarFarmacia.setGeometry(QtCore.QRect(0, 0, 741, 741))
        self.tb_agregarFarmacia.setObjectName("tb_agregarFarmacia")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(340, 230, 160, 95))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tf_Farmacia_Ciudad = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.tf_Farmacia_Ciudad.setObjectName("tf_Farmacia_Ciudad")
        self.verticalLayout_2.addWidget(self.tf_Farmacia_Ciudad)
        self.tf_Farmacia_departamento = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.tf_Farmacia_departamento.setObjectName("tf_Farmacia_departamento")
        self.verticalLayout_2.addWidget(self.tf_Farmacia_departamento)
        self.tf_Farmacia_calle = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.tf_Farmacia_calle.setObjectName("tf_Farmacia_calle")
        self.verticalLayout_2.addWidget(self.tf_Farmacia_calle)
        self.label_2 = QtWidgets.QLabel(self.tab_4)
        self.label_2.setGeometry(QtCore.QRect(220, 60, 231, 31))
        self.label_2.setStyleSheet("font: italic 20pt \"URW Palladio L\";")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(160, 140, 158, 31))
        self.label_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_4.setIndent(0)
        self.label_4.setObjectName("label_4")
        self.bt_Farmacia_Cancelar = QtWidgets.QPushButton(self.tab_4)
        self.bt_Farmacia_Cancelar.setGeometry(QtCore.QRect(320, 530, 101, 41))
        self.bt_Farmacia_Cancelar.setObjectName("bt_Farmacia_Cancelar")
        self.label_3 = QtWidgets.QLabel(self.tab_4)
        self.label_3.setGeometry(QtCore.QRect(240, 190, 158, 25))
        self.label_3.setObjectName("label_3")
        self.bt_Farmacia_asigPropietarios = QtWidgets.QPushButton(self.tab_4)
        self.bt_Farmacia_asigPropietarios.setGeometry(QtCore.QRect(510, 370, 71, 27))
        self.bt_Farmacia_asigPropietarios.setObjectName("bt_Farmacia_asigPropietarios")
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setGeometry(QtCore.QRect(160, 400, 158, 31))
        self.label_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_9.setIndent(0)
        self.label_9.setObjectName("label_9")
        self.cb_Farmacia_farmaceuticos = QtWidgets.QComboBox(self.tab_4)
        self.cb_Farmacia_farmaceuticos.setGeometry(QtCore.QRect(340, 400, 161, 27))
        self.cb_Farmacia_farmaceuticos.setObjectName("cb_Farmacia_farmaceuticos")
        self.bt_Farmacia_Agregar = QtWidgets.QPushButton(self.tab_4)
        self.bt_Farmacia_Agregar.setGeometry(QtCore.QRect(160, 460, 111, 41))
        self.bt_Farmacia_Agregar.setObjectName("bt_Farmacia_Agregar")
        self.tf_Farmacia_codigoFarm = QtWidgets.QLineEdit(self.tab_4)
        self.tf_Farmacia_codigoFarm.setGeometry(QtCore.QRect(340, 140, 158, 27))
        self.tf_Farmacia_codigoFarm.setObjectName("tf_Farmacia_codigoFarm")
        self.bt_Farmacia_asigFarmaceuticos = QtWidgets.QPushButton(self.tab_4)
        self.bt_Farmacia_asigFarmaceuticos.setGeometry(QtCore.QRect(510, 400, 71, 27))
        self.bt_Farmacia_asigFarmaceuticos.setObjectName("bt_Farmacia_asigFarmaceuticos")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(160, 230, 160, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.cb_Farmacia_Propietarios = QtWidgets.QComboBox(self.tab_4)
        self.cb_Farmacia_Propietarios.setGeometry(QtCore.QRect(340, 370, 161, 27))
        self.cb_Farmacia_Propietarios.setObjectName("cb_Farmacia_Propietarios")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(160, 370, 158, 31))
        self.label_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_5.setIndent(0)
        self.label_5.setObjectName("label_5")
        self.bt_Farmacia_Modificar = QtWidgets.QPushButton(self.tab_4)
        self.bt_Farmacia_Modificar.setGeometry(QtCore.QRect(310, 460, 111, 41))
        self.bt_Farmacia_Modificar.setObjectName("bt_Farmacia_Modificar")
        self.bt_Farmacia_Eliminar = QtWidgets.QPushButton(self.tab_4)
        self.bt_Farmacia_Eliminar.setGeometry(QtCore.QRect(470, 460, 111, 41))
        self.bt_Farmacia_Eliminar.setObjectName("bt_Farmacia_Eliminar")
        self.bt_FindFarmacia = QtWidgets.QPushButton(self.tab_4)
        self.bt_FindFarmacia.setGeometry(QtCore.QRect(510, 140, 121, 27))
        self.bt_FindFarmacia.setObjectName("bt_FindFarmacia")
        self.bt_load = QtWidgets.QPushButton(self.tab_4)
        self.bt_load.setGeometry(QtCore.QRect(160, 430, 71, 27))
        self.bt_load.setObjectName("bt_load")
        self.cb_almaneces = QtWidgets.QComboBox(self.tab_4)
        self.cb_almaneces.setGeometry(QtCore.QRect(340, 340, 161, 27))
        self.cb_almaneces.setObjectName("cb_almaneces")
        self.label_74 = QtWidgets.QLabel(self.tab_4)
        self.label_74.setGeometry(QtCore.QRect(160, 340, 158, 31))
        self.label_74.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_74.setIndent(0)
        self.label_74.setObjectName("label_74")
        self.bt_asignaralmancen = QtWidgets.QPushButton(self.tab_4)
        self.bt_asignaralmancen.setGeometry(QtCore.QRect(510, 340, 71, 27))
        self.bt_asignaralmancen.setObjectName("bt_asignaralmancen")
        self.tb_agregarFarmacia.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_15 = QtWidgets.QLabel(self.tab_5)
        self.label_15.setGeometry(QtCore.QRect(250, 20, 241, 31))
        self.label_15.setStyleSheet("font: italic 20pt \"URW Palladio L\";")
        self.label_15.setObjectName("label_15")
        self.tf_Farmacia_CodFarmaciaAlmacenBuscar = QtWidgets.QLineEdit(self.tab_5)
        self.tf_Farmacia_CodFarmaciaAlmacenBuscar.setGeometry(QtCore.QRect(410, 60, 158, 27))
        self.tf_Farmacia_CodFarmaciaAlmacenBuscar.setObjectName("tf_Farmacia_CodFarmaciaAlmacenBuscar")
        self.label_27 = QtWidgets.QLabel(self.tab_5)
        self.label_27.setGeometry(QtCore.QRect(240, 60, 158, 31))
        self.label_27.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_27.setIndent(0)
        self.label_27.setObjectName("label_27")
        self.bt_Farmacia_BuscarProductos = QtWidgets.QPushButton(self.tab_5)
        self.bt_Farmacia_BuscarProductos.setGeometry(QtCore.QRect(580, 60, 111, 31))
        self.bt_Farmacia_BuscarProductos.setObjectName("bt_Farmacia_BuscarProductos")
        self.label_77 = QtWidgets.QLabel(self.tab_5)
        self.label_77.setGeometry(QtCore.QRect(40, 140, 101, 16))
        self.label_77.setObjectName("label_77")
        self.label_90 = QtWidgets.QLabel(self.tab_5)
        self.label_90.setGeometry(QtCore.QRect(240, 100, 158, 31))
        self.label_90.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_90.setIndent(0)
        self.label_90.setObjectName("label_90")
        self.tf_alamacenfarma = QtWidgets.QLineEdit(self.tab_5)
        self.tf_alamacenfarma.setGeometry(QtCore.QRect(410, 100, 158, 27))
        self.tf_alamacenfarma.setObjectName("tf_alamacenfarma")
        self.bt_almacen_farmacia = QtWidgets.QPushButton(self.tab_5)
        self.bt_almacen_farmacia.setGeometry(QtCore.QRect(580, 100, 111, 31))
        self.bt_almacen_farmacia.setObjectName("bt_almacen_farmacia")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget.setGeometry(QtCore.QRect(190, 170, 531, 461))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label_91 = QtWidgets.QLabel(self.tab_5)
        self.label_91.setGeometry(QtCore.QRect(200, 140, 101, 16))
        self.label_91.setObjectName("label_91")
        self.tb_almacenesfarma = QtWidgets.QTableWidget(self.tab_5)
        self.tb_almacenesfarma.setGeometry(QtCore.QRect(20, 170, 121, 261))
        self.tb_almacenesfarma.setObjectName("tb_almacenesfarma")
        self.tb_almacenesfarma.setColumnCount(0)
        self.tb_almacenesfarma.setRowCount(0)
        self.tb_agregarFarmacia.addTab(self.tab_5, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 141, 721, 551))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.tb_agregarFarmacia.addTab(self.tab_3, "")
        self.tb_agregarFarmacia.raise_()
        self.tabPrincipal.addTab(self.tabCrudFarmacias, "")
        self.Almacenes = QtWidgets.QWidget()
        self.Almacenes.setStyleSheet("Almacences")
        self.Almacenes.setObjectName("Almacenes")
        self.bt_agregarAlmacen = QtWidgets.QPushButton(self.Almacenes)
        self.bt_agregarAlmacen.setGeometry(QtCore.QRect(220, 150, 97, 27))
        self.bt_agregarAlmacen.setObjectName("bt_agregarAlmacen")
        self.label_75 = QtWidgets.QLabel(self.Almacenes)
        self.label_75.setGeometry(QtCore.QRect(130, 70, 66, 17))
        self.label_75.setObjectName("label_75")
        self.tf_codigo_almacenes = QtWidgets.QLineEdit(self.Almacenes)
        self.tf_codigo_almacenes.setGeometry(QtCore.QRect(210, 70, 158, 27))
        self.tf_codigo_almacenes.setObjectName("tf_codigo_almacenes")
        self.tabPrincipal.addTab(self.Almacenes, "")
        self.tabCrudFarmaceuticos = QtWidgets.QWidget()
        self.tabCrudFarmaceuticos.setObjectName("tabCrudFarmaceuticos")
        self.label_16 = QtWidgets.QLabel(self.tabCrudFarmaceuticos)
        self.label_16.setGeometry(QtCore.QRect(170, 120, 131, 26))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tabCrudFarmaceuticos)
        self.label_17.setGeometry(QtCore.QRect(240, 40, 261, 31))
        self.label_17.setStyleSheet("font: italic 20pt \"URW Palladio L\";")
        self.label_17.setObjectName("label_17")
        self.tf_Farmaceutico_nombre = QtWidgets.QLineEdit(self.tabCrudFarmaceuticos)
        self.tf_Farmaceutico_nombre.setGeometry(QtCore.QRect(320, 120, 158, 27))
        self.tf_Farmaceutico_nombre.setObjectName("tf_Farmaceutico_nombre")
        self.label_18 = QtWidgets.QLabel(self.tabCrudFarmaceuticos)
        self.label_18.setGeometry(QtCore.QRect(230, 170, 71, 26))
        self.label_18.setObjectName("label_18")
        self.tf_Farmaceutico_direccion = QtWidgets.QLineEdit(self.tabCrudFarmaceuticos)
        self.tf_Farmaceutico_direccion.setGeometry(QtCore.QRect(320, 170, 158, 27))
        self.tf_Farmaceutico_direccion.setObjectName("tf_Farmaceutico_direccion")
        self.label_19 = QtWidgets.QLabel(self.tabCrudFarmaceuticos)
        self.label_19.setGeometry(QtCore.QRect(260, 220, 41, 26))
        self.label_19.setObjectName("label_19")
        self.tf_Farmaceutico_edad = QtWidgets.QLineEdit(self.tabCrudFarmaceuticos)
        self.tf_Farmaceutico_edad.setGeometry(QtCore.QRect(320, 220, 158, 27))
        self.tf_Farmaceutico_edad.setObjectName("tf_Farmaceutico_edad")
        self.label_20 = QtWidgets.QLabel(self.tabCrudFarmaceuticos)
        self.label_20.setGeometry(QtCore.QRect(270, 340, 16, 26))
        self.label_20.setObjectName("label_20")
        self.tf_Farmaceutico_id = QtWidgets.QLineEdit(self.tabCrudFarmaceuticos)
        self.tf_Farmaceutico_id.setGeometry(QtCore.QRect(320, 340, 158, 27))
        self.tf_Farmaceutico_id.setObjectName("tf_Farmaceutico_id")
        self.bt_Farmaceutico_cancelar = QtWidgets.QPushButton(self.tabCrudFarmaceuticos)
        self.bt_Farmaceutico_cancelar.setGeometry(QtCore.QRect(320, 480, 101, 41))
        self.bt_Farmaceutico_cancelar.setObjectName("bt_Farmaceutico_cancelar")
        self.bt_Farmaceutico_agregar = QtWidgets.QPushButton(self.tabCrudFarmaceuticos)
        self.bt_Farmaceutico_agregar.setGeometry(QtCore.QRect(160, 390, 111, 41))
        self.bt_Farmaceutico_agregar.setObjectName("bt_Farmaceutico_agregar")
        self.bt_Farmaceutico_Modificar = QtWidgets.QPushButton(self.tabCrudFarmaceuticos)
        self.bt_Farmaceutico_Modificar.setGeometry(QtCore.QRect(310, 390, 111, 41))
        self.bt_Farmaceutico_Modificar.setObjectName("bt_Farmaceutico_Modificar")
        self.bt_Farmaceutico_Eliminar = QtWidgets.QPushButton(self.tabCrudFarmaceuticos)
        self.bt_Farmaceutico_Eliminar.setGeometry(QtCore.QRect(460, 390, 111, 41))
        self.bt_Farmaceutico_Eliminar.setObjectName("bt_Farmaceutico_Eliminar")
        self.bt_FindFarmaceutico = QtWidgets.QPushButton(self.tabCrudFarmaceuticos)
        self.bt_FindFarmaceutico.setGeometry(QtCore.QRect(500, 120, 161, 27))
        self.bt_FindFarmaceutico.setObjectName("bt_FindFarmaceutico")
        self.tabPrincipal_2 = QtWidgets.QTabWidget(self.tabCrudFarmaceuticos)
        self.tabPrincipal_2.setGeometry(QtCore.QRect(-10, -30, 751, 771))
        self.tabPrincipal_2.setObjectName("tabPrincipal_2")
        self.tabCrudFarmacias_2 = QtWidgets.QWidget()
        self.tabCrudFarmacias_2.setObjectName("tabCrudFarmacias_2")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tabCrudFarmacias_2)
        self.tabWidget_3.setGeometry(QtCore.QRect(0, 0, 731, 631))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_8)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(340, 230, 160, 95))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tf_Farmacia_Ciudad_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.tf_Farmacia_Ciudad_2.setObjectName("tf_Farmacia_Ciudad_2")
        self.verticalLayout_3.addWidget(self.tf_Farmacia_Ciudad_2)
        self.tf_Farmacia_departamento_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.tf_Farmacia_departamento_2.setObjectName("tf_Farmacia_departamento_2")
        self.verticalLayout_3.addWidget(self.tf_Farmacia_departamento_2)
        self.tf_Farmacia_calle_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.tf_Farmacia_calle_2.setObjectName("tf_Farmacia_calle_2")
        self.verticalLayout_3.addWidget(self.tf_Farmacia_calle_2)
        self.label_38 = QtWidgets.QLabel(self.tab_8)
        self.label_38.setGeometry(QtCore.QRect(220, 60, 231, 31))
        self.label_38.setStyleSheet("font: italic 20pt \"URW Palladio L\";")
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.tab_8)
        self.label_39.setGeometry(QtCore.QRect(160, 140, 158, 31))
        self.label_39.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_39.setIndent(0)
        self.label_39.setObjectName("label_39")
        self.bt_Farmacia_Cancelar_2 = QtWidgets.QPushButton(self.tab_8)
        self.bt_Farmacia_Cancelar_2.setGeometry(QtCore.QRect(320, 530, 101, 41))
        self.bt_Farmacia_Cancelar_2.setObjectName("bt_Farmacia_Cancelar_2")
        self.label_40 = QtWidgets.QLabel(self.tab_8)
        self.label_40.setGeometry(QtCore.QRect(240, 190, 158, 25))
        self.label_40.setObjectName("label_40")
        self.bt_Farmacia_asigPropietarios_2 = QtWidgets.QPushButton(self.tab_8)
        self.bt_Farmacia_asigPropietarios_2.setGeometry(QtCore.QRect(510, 350, 71, 27))
        self.bt_Farmacia_asigPropietarios_2.setObjectName("bt_Farmacia_asigPropietarios_2")
        self.label_41 = QtWidgets.QLabel(self.tab_8)
        self.label_41.setGeometry(QtCore.QRect(160, 380, 158, 31))
        self.label_41.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_41.setIndent(0)
        self.label_41.setObjectName("label_41")
        self.cb_Farmacia_farmaceuticos_2 = QtWidgets.QComboBox(self.tab_8)
        self.cb_Farmacia_farmaceuticos_2.setGeometry(QtCore.QRect(340, 380, 161, 27))
        self.cb_Farmacia_farmaceuticos_2.setObjectName("cb_Farmacia_farmaceuticos_2")
        self.bt_Farmacia_Agregar_2 = QtWidgets.QPushButton(self.tab_8)
        self.bt_Farmacia_Agregar_2.setGeometry(QtCore.QRect(160, 460, 111, 41))
        self.bt_Farmacia_Agregar_2.setObjectName("bt_Farmacia_Agregar_2")
        self.tf_Farmacia_codigoFarm_2 = QtWidgets.QLineEdit(self.tab_8)
        self.tf_Farmacia_codigoFarm_2.setGeometry(QtCore.QRect(340, 140, 158, 27))
        self.tf_Farmacia_codigoFarm_2.setObjectName("tf_Farmacia_codigoFarm_2")
        self.bt_Farmacia_asigFarmaceuticos_2 = QtWidgets.QPushButton(self.tab_8)
        self.bt_Farmacia_asigFarmaceuticos_2.setGeometry(QtCore.QRect(510, 380, 71, 27))
        self.bt_Farmacia_asigFarmaceuticos_2.setObjectName("bt_Farmacia_asigFarmaceuticos_2")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab_8)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(160, 230, 160, 91))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_42 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_4.addWidget(self.label_42)
        self.label_43 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_4.addWidget(self.label_43)
        self.label_44 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_4.addWidget(self.label_44)
        self.cb_Farmacia_Propietarios_2 = QtWidgets.QComboBox(self.tab_8)
        self.cb_Farmacia_Propietarios_2.setGeometry(QtCore.QRect(340, 350, 161, 27))
        self.cb_Farmacia_Propietarios_2.setObjectName("cb_Farmacia_Propietarios_2")
        self.label_45 = QtWidgets.QLabel(self.tab_8)
        self.label_45.setGeometry(QtCore.QRect(160, 350, 158, 31))
        self.label_45.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_45.setIndent(0)
        self.label_45.setObjectName("label_45")
        self.bt_Farmacia_Modificar_2 = QtWidgets.QPushButton(self.tab_8)
        self.bt_Farmacia_Modificar_2.setGeometry(QtCore.QRect(310, 460, 111, 41))
        self.bt_Farmacia_Modificar_2.setObjectName("bt_Farmacia_Modificar_2")
        self.bt_Farmacia_Eliminar_2 = QtWidgets.QPushButton(self.tab_8)
        self.bt_Farmacia_Eliminar_2.setGeometry(QtCore.QRect(470, 460, 111, 41))
        self.bt_Farmacia_Eliminar_2.setObjectName("bt_Farmacia_Eliminar_2")
        self.bt_FindFarmacia_2 = QtWidgets.QPushButton(self.tab_8)
        self.bt_FindFarmacia_2.setGeometry(QtCore.QRect(510, 140, 121, 27))
        self.bt_FindFarmacia_2.setObjectName("bt_FindFarmacia_2")
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.label_46 = QtWidgets.QLabel(self.tab_9)
        self.label_46.setGeometry(QtCore.QRect(250, 40, 241, 31))
        self.label_46.setStyleSheet("font: italic 20pt \"URW Palladio L\";")
        self.label_46.setObjectName("label_46")
        self.tableView_2 = QtWidgets.QTableView(self.tab_9)
        self.tableView_2.setGeometry(QtCore.QRect(50, 110, 601, 321))
        self.tableView_2.setObjectName("tableView_2")
        self.tf_Farmacia_CodFarmaciaAlmacenBuscar_2 = QtWidgets.QLineEdit(self.tab_9)
        self.tf_Farmacia_CodFarmaciaAlmacenBuscar_2.setGeometry(QtCore.QRect(280, 470, 158, 27))
        self.tf_Farmacia_CodFarmaciaAlmacenBuscar_2.setObjectName("tf_Farmacia_CodFarmaciaAlmacenBuscar_2")
        self.label_47 = QtWidgets.QLabel(self.tab_9)
        self.label_47.setGeometry(QtCore.QRect(100, 470, 158, 31))
        self.label_47.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_47.setIndent(0)
        self.label_47.setObjectName("label_47")
        self.bt_Farmacia_BuscarProductos_2 = QtWidgets.QPushButton(self.tab_9)
        self.bt_Farmacia_BuscarProductos_2.setGeometry(QtCore.QRect(460, 460, 111, 41))
        self.bt_Farmacia_BuscarProductos_2.setObjectName("bt_Farmacia_BuscarProductos_2")
        self.tabWidget_3.addTab(self.tab_9, "")
        self.tabPrincipal_2.addTab(self.tabCrudFarmacias_2, "")
        self.tabCrudFarmaceuticos_2 = QtWidgets.QWidget()
        self.tabCrudFarmaceuticos_2.setObjectName("tabCrudFarmaceuticos_2")
        self.label_48 = QtWidgets.QLabel(self.tabCrudFarmaceuticos_2)
        self.label_48.setGeometry(QtCore.QRect(180, 170, 131, 26))
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.tabCrudFarmaceuticos_2)
        self.label_49.setGeometry(QtCore.QRect(240, 40, 261, 31))
        self.label_49.setStyleSheet("font: italic 20pt \"URW Palladio L\";")
        self.label_49.setObjectName("label_49")
        self.tf_Farmaceutico_nombre_2 = QtWidgets.QLineEdit(self.tabCrudFarmaceuticos_2)
        self.tf_Farmaceutico_nombre_2.setGeometry(QtCore.QRect(330, 170, 158, 27))
        self.tf_Farmaceutico_nombre_2.setObjectName("tf_Farmaceutico_nombre_2")
        self.label_50 = QtWidgets.QLabel(self.tabCrudFarmaceuticos_2)
        self.label_50.setGeometry(QtCore.QRect(240, 220, 71, 26))
        self.label_50.setObjectName("label_50")
        self.tf_Farmaceutico_direccion_2 = QtWidgets.QLineEdit(self.tabCrudFarmaceuticos_2)
        self.tf_Farmaceutico_direccion_2.setGeometry(QtCore.QRect(330, 220, 158, 27))
        self.tf_Farmaceutico_direccion_2.setObjectName("tf_Farmaceutico_direccion_2")
        self.label_51 = QtWidgets.QLabel(self.tabCrudFarmaceuticos_2)
        self.label_51.setGeometry(QtCore.QRect(270, 270, 41, 26))
        self.label_51.setObjectName("label_51")
        self.tf_Farmaceutico_edad_2 = QtWidgets.QLineEdit(self.tabCrudFarmaceuticos_2)
        self.tf_Farmaceutico_edad_2.setGeometry(QtCore.QRect(330, 270, 158, 27))
        self.tf_Farmaceutico_edad_2.setObjectName("tf_Farmaceutico_edad_2")
        self.label_52 = QtWidgets.QLabel(self.tabCrudFarmaceuticos_2)
        self.label_52.setGeometry(QtCore.QRect(280, 120, 16, 26))
        self.label_52.setObjectName("label_52")
        self.tf_Farmaceutico_id_2 = QtWidgets.QLineEdit(self.tabCrudFarmaceuticos_2)
        self.tf_Farmaceutico_id_2.setGeometry(QtCore.QRect(330, 120, 158, 27))
        self.tf_Farmaceutico_id_2.setObjectName("tf_Farmaceutico_id_2")
        self.bt_Farmaceutico_cancelar_2 = QtWidgets.QPushButton(self.tabCrudFarmaceuticos_2)
        self.bt_Farmaceutico_cancelar_2.setGeometry(QtCore.QRect(320, 480, 101, 41))
        self.bt_Farmaceutico_cancelar_2.setObjectName("bt_Farmaceutico_cancelar_2")
        self.bt_Farmaceutico_agregar_2 = QtWidgets.QPushButton(self.tabCrudFarmaceuticos_2)
        self.bt_Farmaceutico_agregar_2.setGeometry(QtCore.QRect(160, 390, 111, 41))
        self.bt_Farmaceutico_agregar_2.setObjectName("bt_Farmaceutico_agregar_2")
        self.bt_Farmaceutico_Modificar_2 = QtWidgets.QPushButton(self.tabCrudFarmaceuticos_2)
        self.bt_Farmaceutico_Modificar_2.setGeometry(QtCore.QRect(310, 390, 111, 41))
        self.bt_Farmaceutico_Modificar_2.setObjectName("bt_Farmaceutico_Modificar_2")
        self.bt_Farmaceutico_Eliminar_2 = QtWidgets.QPushButton(self.tabCrudFarmaceuticos_2)
        self.bt_Farmaceutico_Eliminar_2.setGeometry(QtCore.QRect(460, 390, 111, 41))
        self.bt_Farmaceutico_Eliminar_2.setObjectName("bt_Farmaceutico_Eliminar_2")
        self.bt_FindFarmaceutico_2 = QtWidgets.QPushButton(self.tabCrudFarmaceuticos_2)
        self.bt_FindFarmaceutico_2.setGeometry(QtCore.QRect(500, 120, 161, 27))
        self.bt_FindFarmaceutico_2.setObjectName("bt_FindFarmaceutico_2")
        self.tabPrincipal_2.addTab(self.tabCrudFarmaceuticos_2, "")
        self.tabCrudPropietarios_2 = QtWidgets.QWidget()
        self.tabCrudPropietarios_2.setObjectName("tabCrudPropietarios_2")
        self.label_53 = QtWidgets.QLabel(self.tabCrudPropietarios_2)
        self.label_53.setGeometry(QtCore.QRect(240, 40, 261, 31))
        self.label_53.setStyleSheet("font: italic 20pt \"URW Palladio L\";")
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.tabCrudPropietarios_2)
        self.label_54.setGeometry(QtCore.QRect(180, 120, 131, 26))
        self.label_54.setObjectName("label_54")
        self.tf_propietario_nombre_2 = QtWidgets.QLineEdit(self.tabCrudPropietarios_2)
        self.tf_propietario_nombre_2.setGeometry(QtCore.QRect(340, 120, 158, 27))
        self.tf_propietario_nombre_2.setObjectName("tf_propietario_nombre_2")
        self.label_55 = QtWidgets.QLabel(self.tabCrudPropietarios_2)
        self.label_55.setGeometry(QtCore.QRect(270, 220, 41, 26))
        self.label_55.setObjectName("label_55")
        self.tf_propietario_edad_2 = QtWidgets.QLineEdit(self.tabCrudPropietarios_2)
        self.tf_propietario_edad_2.setGeometry(QtCore.QRect(340, 220, 158, 27))
        self.tf_propietario_edad_2.setObjectName("tf_propietario_edad_2")
        self.tf_propietario_direccion_2 = QtWidgets.QLineEdit(self.tabCrudPropietarios_2)
        self.tf_propietario_direccion_2.setGeometry(QtCore.QRect(340, 170, 158, 27))
        self.tf_propietario_direccion_2.setObjectName("tf_propietario_direccion_2")
        self.label_56 = QtWidgets.QLabel(self.tabCrudPropietarios_2)
        self.label_56.setGeometry(QtCore.QRect(240, 170, 71, 26))
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.tabCrudPropietarios_2)
        self.label_57.setGeometry(QtCore.QRect(280, 270, 16, 26))
        self.label_57.setObjectName("label_57")
        self.tf_propietario_id_2 = QtWidgets.QLineEdit(self.tabCrudPropietarios_2)
        self.tf_propietario_id_2.setGeometry(QtCore.QRect(340, 270, 158, 27))
        self.tf_propietario_id_2.setObjectName("tf_propietario_id_2")
        self.bt_propietario_cancelar_2 = QtWidgets.QPushButton(self.tabCrudPropietarios_2)
        self.bt_propietario_cancelar_2.setGeometry(QtCore.QRect(320, 430, 101, 41))
        self.bt_propietario_cancelar_2.setObjectName("bt_propietario_cancelar_2")
        self.bt_propietario_agregar_2 = QtWidgets.QPushButton(self.tabCrudPropietarios_2)
        self.bt_propietario_agregar_2.setGeometry(QtCore.QRect(150, 350, 111, 41))
        self.bt_propietario_agregar_2.setObjectName("bt_propietario_agregar_2")
        self.bt_propietario_Modificar_2 = QtWidgets.QPushButton(self.tabCrudPropietarios_2)
        self.bt_propietario_Modificar_2.setGeometry(QtCore.QRect(320, 350, 111, 41))
        self.bt_propietario_Modificar_2.setObjectName("bt_propietario_Modificar_2")
        self.bt_propietario_Eliminar_2 = QtWidgets.QPushButton(self.tabCrudPropietarios_2)
        self.bt_propietario_Eliminar_2.setGeometry(QtCore.QRect(510, 350, 111, 41))
        self.bt_propietario_Eliminar_2.setObjectName("bt_propietario_Eliminar_2")
        self.bt_FindPropietario_2 = QtWidgets.QPushButton(self.tabCrudPropietarios_2)
        self.bt_FindPropietario_2.setGeometry(QtCore.QRect(510, 120, 161, 27))
        self.bt_FindPropietario_2.setObjectName("bt_FindPropietario_2")
        self.tabPrincipal_2.addTab(self.tabCrudPropietarios_2, "")
        self.tabCrudLaboratorios_2 = QtWidgets.QWidget()
        self.tabCrudLaboratorios_2.setObjectName("tabCrudLaboratorios_2")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tabCrudLaboratorios_2)
        self.tabWidget_4.setGeometry(QtCore.QRect(0, 0, 741, 581))
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.label_58 = QtWidgets.QLabel(self.tab_10)
        self.label_58.setGeometry(QtCore.QRect(250, 30, 261, 31))
        self.label_58.setStyleSheet("font: italic 20pt \"URW Palladio L\";")
        self.label_58.setObjectName("label_58")
        self.tf_Laboratorio_id_2 = QtWidgets.QLineEdit(self.tab_10)
        self.tf_Laboratorio_id_2.setGeometry(QtCore.QRect(350, 110, 158, 27))
        self.tf_Laboratorio_id_2.setObjectName("tf_Laboratorio_id_2")
        self.label_59 = QtWidgets.QLabel(self.tab_10)
        self.label_59.setGeometry(QtCore.QRect(300, 110, 21, 26))
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.tab_10)
        self.label_60.setGeometry(QtCore.QRect(260, 150, 61, 26))
        self.label_60.setObjectName("label_60")
        self.tf_Laboratorio_nombre_2 = QtWidgets.QLineEdit(self.tab_10)
        self.tf_Laboratorio_nombre_2.setGeometry(QtCore.QRect(350, 150, 158, 27))
        self.tf_Laboratorio_nombre_2.setObjectName("tf_Laboratorio_nombre_2")
        self.bt_Laboratorio_agregar_2 = QtWidgets.QPushButton(self.tab_10)
        self.bt_Laboratorio_agregar_2.setGeometry(QtCore.QRect(150, 240, 121, 41))
        self.bt_Laboratorio_agregar_2.setObjectName("bt_Laboratorio_agregar_2")
        self.bt_Laboratorio_cancelar_2 = QtWidgets.QPushButton(self.tab_10)
        self.bt_Laboratorio_cancelar_2.setGeometry(QtCore.QRect(300, 320, 151, 41))
        self.bt_Laboratorio_cancelar_2.setObjectName("bt_Laboratorio_cancelar_2")
        self.bt_Laboratorio_Modificar_2 = QtWidgets.QPushButton(self.tab_10)
        self.bt_Laboratorio_Modificar_2.setGeometry(QtCore.QRect(310, 240, 121, 41))
        self.bt_Laboratorio_Modificar_2.setObjectName("bt_Laboratorio_Modificar_2")
        self.bt_Laboratorio_Eliminar_2 = QtWidgets.QPushButton(self.tab_10)
        self.bt_Laboratorio_Eliminar_2.setGeometry(QtCore.QRect(460, 240, 121, 41))
        self.bt_Laboratorio_Eliminar_2.setObjectName("bt_Laboratorio_Eliminar_2")
        self.bt_FindLaboratorio_2 = QtWidgets.QPushButton(self.tab_10)
        self.bt_FindLaboratorio_2.setGeometry(QtCore.QRect(520, 110, 161, 27))
        self.bt_FindLaboratorio_2.setObjectName("bt_FindLaboratorio_2")
        self.tabWidget_4.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.label_61 = QtWidgets.QLabel(self.tab_11)
        self.label_61.setGeometry(QtCore.QRect(250, 50, 211, 31))
        self.label_61.setStyleSheet("font: italic 20pt \"URW Palladio L\";")
        self.label_61.setObjectName("label_61")
        self.tf_Laboratorio_IdProduct_2 = QtWidgets.QLineEdit(self.tab_11)
        self.tf_Laboratorio_IdProduct_2.setGeometry(QtCore.QRect(350, 130, 158, 27))
        self.tf_Laboratorio_IdProduct_2.setObjectName("tf_Laboratorio_IdProduct_2")
        self.label_62 = QtWidgets.QLabel(self.tab_11)
        self.label_62.setGeometry(QtCore.QRect(190, 130, 131, 26))
        self.label_62.setObjectName("label_62")
        self.tf_Laboratorio_cantidadProduct_2 = QtWidgets.QLineEdit(self.tab_11)
        self.tf_Laboratorio_cantidadProduct_2.setGeometry(QtCore.QRect(350, 170, 158, 27))
        self.tf_Laboratorio_cantidadProduct_2.setObjectName("tf_Laboratorio_cantidadProduct_2")
        self.label_63 = QtWidgets.QLabel(self.tab_11)
        self.label_63.setGeometry(QtCore.QRect(190, 170, 131, 26))
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.tab_11)
        self.label_64.setGeometry(QtCore.QRect(190, 210, 131, 26))
        self.label_64.setObjectName("label_64")
        self.tf_Laboratorio_costoVentaProducto_2 = QtWidgets.QLineEdit(self.tab_11)
        self.tf_Laboratorio_costoVentaProducto_2.setGeometry(QtCore.QRect(350, 210, 158, 27))
        self.tf_Laboratorio_costoVentaProducto_2.setObjectName("tf_Laboratorio_costoVentaProducto_2")
        self.bt_Laboratorio_AgregarProducto_2 = QtWidgets.QPushButton(self.tab_11)
        self.bt_Laboratorio_AgregarProducto_2.setGeometry(QtCore.QRect(290, 300, 151, 41))
        self.bt_Laboratorio_AgregarProducto_2.setObjectName("bt_Laboratorio_AgregarProducto_2")
        self.tabWidget_4.addTab(self.tab_11, "")
        self.tabPrincipal_2.addTab(self.tabCrudLaboratorios_2, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_65 = QtWidgets.QLabel(self.tab_2)
        self.label_65.setGeometry(QtCore.QRect(280, 130, 20, 20))
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.tab_2)
        self.label_66.setGeometry(QtCore.QRect(240, 180, 61, 20))
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.tab_2)
        self.label_67.setGeometry(QtCore.QRect(220, 230, 71, 20))
        self.label_67.setObjectName("label_67")
        self.label_68 = QtWidgets.QLabel(self.tab_2)
        self.label_68.setGeometry(QtCore.QRect(190, 280, 111, 20))
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(self.tab_2)
        self.label_69.setGeometry(QtCore.QRect(190, 330, 111, 20))
        self.label_69.setObjectName("label_69")
        self.tf_Producto_id_2 = QtWidgets.QLineEdit(self.tab_2)
        self.tf_Producto_id_2.setGeometry(QtCore.QRect(330, 130, 158, 27))
        self.tf_Producto_id_2.setObjectName("tf_Producto_id_2")
        self.tf_Producto_nombre_2 = QtWidgets.QLineEdit(self.tab_2)
        self.tf_Producto_nombre_2.setGeometry(QtCore.QRect(330, 180, 158, 27))
        self.tf_Producto_nombre_2.setObjectName("tf_Producto_nombre_2")
        self.tf_Producto_Fabricante_2 = QtWidgets.QLineEdit(self.tab_2)
        self.tf_Producto_Fabricante_2.setGeometry(QtCore.QRect(330, 230, 158, 27))
        self.tf_Producto_Fabricante_2.setObjectName("tf_Producto_Fabricante_2")
        self.tf_Producto_precioCoste_2 = QtWidgets.QLineEdit(self.tab_2)
        self.tf_Producto_precioCoste_2.setGeometry(QtCore.QRect(330, 280, 158, 27))
        self.tf_Producto_precioCoste_2.setObjectName("tf_Producto_precioCoste_2")
        self.tf_Producto_PrecioVenta_2 = QtWidgets.QLineEdit(self.tab_2)
        self.tf_Producto_PrecioVenta_2.setGeometry(QtCore.QRect(330, 330, 158, 27))
        self.tf_Producto_PrecioVenta_2.setObjectName("tf_Producto_PrecioVenta_2")
        self.label_70 = QtWidgets.QLabel(self.tab_2)
        self.label_70.setGeometry(QtCore.QRect(40, 490, 261, 20))
        self.label_70.setObjectName("label_70")
        self.label_71 = QtWidgets.QLabel(self.tab_2)
        self.label_71.setGeometry(QtCore.QRect(250, 40, 261, 31))
        self.label_71.setStyleSheet("font: italic 20pt \"URW Palladio L\";")
        self.label_71.setObjectName("label_71")
        self.bt_Producto_cancelar_2 = QtWidgets.QPushButton(self.tab_2)
        self.bt_Producto_cancelar_2.setGeometry(QtCore.QRect(330, 670, 101, 41))
        self.bt_Producto_cancelar_2.setObjectName("bt_Producto_cancelar_2")
        self.bt_Producto_agregar_2 = QtWidgets.QPushButton(self.tab_2)
        self.bt_Producto_agregar_2.setGeometry(QtCore.QRect(130, 590, 111, 41))
        self.bt_Producto_agregar_2.setObjectName("bt_Producto_agregar_2")
        self.cb_Producto_TieneProteccion_2 = QtWidgets.QComboBox(self.tab_2)
        self.cb_Producto_TieneProteccion_2.setGeometry(QtCore.QRect(330, 490, 151, 27))
        self.cb_Producto_TieneProteccion_2.setObjectName("cb_Producto_TieneProteccion_2")
        self.cb_Producto_TieneProteccion_2.addItem("")
        self.cb_Producto_TieneProteccion_2.addItem("")
        self.tf_Producto_Categoria_2 = QtWidgets.QLineEdit(self.tab_2)
        self.tf_Producto_Categoria_2.setGeometry(QtCore.QRect(330, 370, 158, 27))
        self.tf_Producto_Categoria_2.setObjectName("tf_Producto_Categoria_2")
        self.label_72 = QtWidgets.QLabel(self.tab_2)
        self.label_72.setGeometry(QtCore.QRect(230, 370, 71, 20))
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QLabel(self.tab_2)
        self.label_73.setGeometry(QtCore.QRect(130, 410, 171, 20))
        self.label_73.setObjectName("label_73")
        self.tf_Producto_DescripcionProducto_2 = QtWidgets.QPlainTextEdit(self.tab_2)
        self.tf_Producto_DescripcionProducto_2.setGeometry(QtCore.QRect(330, 410, 251, 75))
        self.tf_Producto_DescripcionProducto_2.setObjectName("tf_Producto_DescripcionProducto_2")
        self.bt_Producto_Modificar_2 = QtWidgets.QPushButton(self.tab_2)
        self.bt_Producto_Modificar_2.setGeometry(QtCore.QRect(320, 590, 111, 41))
        self.bt_Producto_Modificar_2.setObjectName("bt_Producto_Modificar_2")
        self.bt_Producto_Eliminar_2 = QtWidgets.QPushButton(self.tab_2)
        self.bt_Producto_Eliminar_2.setGeometry(QtCore.QRect(520, 590, 111, 41))
        self.bt_Producto_Eliminar_2.setObjectName("bt_Producto_Eliminar_2")
        self.bt_FindProducto_2 = QtWidgets.QPushButton(self.tab_2)
        self.bt_FindProducto_2.setGeometry(QtCore.QRect(500, 130, 161, 27))
        self.bt_FindProducto_2.setObjectName("bt_FindProducto_2")
        self.tabPrincipal_2.addTab(self.tab_2, "")
        self.tabPrincipal.addTab(self.tabCrudFarmaceuticos, "")
        self.tabCrudPropietarios = QtWidgets.QWidget()
        self.tabCrudPropietarios.setObjectName("tabCrudPropietarios")
        self.label_21 = QtWidgets.QLabel(self.tabCrudPropietarios)
        self.label_21.setGeometry(QtCore.QRect(240, 40, 261, 31))
        self.label_21.setStyleSheet("font: italic 20pt \"URW Palladio L\";")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tabCrudPropietarios)
        self.label_22.setGeometry(QtCore.QRect(170, 160, 131, 26))
        self.label_22.setObjectName("label_22")
        self.tf_propietario_nombre = QtWidgets.QLineEdit(self.tabCrudPropietarios)
        self.tf_propietario_nombre.setGeometry(QtCore.QRect(330, 160, 158, 27))
        self.tf_propietario_nombre.setObjectName("tf_propietario_nombre")
        self.label_24 = QtWidgets.QLabel(self.tabCrudPropietarios)
        self.label_24.setGeometry(QtCore.QRect(260, 260, 41, 26))
        self.label_24.setObjectName("label_24")
        self.tf_propietario_edad = QtWidgets.QLineEdit(self.tabCrudPropietarios)
        self.tf_propietario_edad.setGeometry(QtCore.QRect(330, 260, 158, 27))
        self.tf_propietario_edad.setObjectName("tf_propietario_edad")
        self.tf_propietario_direccion = QtWidgets.QLineEdit(self.tabCrudPropietarios)
        self.tf_propietario_direccion.setGeometry(QtCore.QRect(330, 210, 158, 27))
        self.tf_propietario_direccion.setObjectName("tf_propietario_direccion")
        self.label_25 = QtWidgets.QLabel(self.tabCrudPropietarios)
        self.label_25.setGeometry(QtCore.QRect(230, 210, 71, 26))
        self.label_25.setObjectName("label_25")
        self.label_23 = QtWidgets.QLabel(self.tabCrudPropietarios)
        self.label_23.setGeometry(QtCore.QRect(270, 120, 16, 26))
        self.label_23.setObjectName("label_23")
        self.tf_propietario_id = QtWidgets.QLineEdit(self.tabCrudPropietarios)
        self.tf_propietario_id.setGeometry(QtCore.QRect(330, 120, 158, 27))
        self.tf_propietario_id.setObjectName("tf_propietario_id")
        self.bt_propietario_cancelar = QtWidgets.QPushButton(self.tabCrudPropietarios)
        self.bt_propietario_cancelar.setGeometry(QtCore.QRect(320, 430, 101, 41))
        self.bt_propietario_cancelar.setObjectName("bt_propietario_cancelar")
        self.bt_propietario_agregar = QtWidgets.QPushButton(self.tabCrudPropietarios)
        self.bt_propietario_agregar.setGeometry(QtCore.QRect(150, 350, 111, 41))
        self.bt_propietario_agregar.setObjectName("bt_propietario_agregar")
        self.bt_propietario_Modificar = QtWidgets.QPushButton(self.tabCrudPropietarios)
        self.bt_propietario_Modificar.setGeometry(QtCore.QRect(320, 350, 111, 41))
        self.bt_propietario_Modificar.setObjectName("bt_propietario_Modificar")
        self.bt_propietario_Eliminar = QtWidgets.QPushButton(self.tabCrudPropietarios)
        self.bt_propietario_Eliminar.setGeometry(QtCore.QRect(510, 350, 111, 41))
        self.bt_propietario_Eliminar.setObjectName("bt_propietario_Eliminar")
        self.bt_FindPropietario = QtWidgets.QPushButton(self.tabCrudPropietarios)
        self.bt_FindPropietario.setGeometry(QtCore.QRect(510, 120, 161, 27))
        self.bt_FindPropietario.setObjectName("bt_FindPropietario")
        self.tabPrincipal.addTab(self.tabCrudPropietarios, "")
        self.tabCrudLaboratorios = QtWidgets.QWidget()
        self.tabCrudLaboratorios.setObjectName("tabCrudLaboratorios")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tabCrudLaboratorios)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 741, 581))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_28 = QtWidgets.QLabel(self.tab_6)
        self.label_28.setGeometry(QtCore.QRect(250, 30, 261, 31))
        self.label_28.setStyleSheet("font: italic 20pt \"URW Palladio L\";")
        self.label_28.setObjectName("label_28")
        self.tf_Laboratorio_id = QtWidgets.QLineEdit(self.tab_6)
        self.tf_Laboratorio_id.setGeometry(QtCore.QRect(350, 110, 158, 27))
        self.tf_Laboratorio_id.setObjectName("tf_Laboratorio_id")
        self.label_30 = QtWidgets.QLabel(self.tab_6)
        self.label_30.setGeometry(QtCore.QRect(300, 110, 21, 26))
        self.label_30.setObjectName("label_30")
        self.label_33 = QtWidgets.QLabel(self.tab_6)
        self.label_33.setGeometry(QtCore.QRect(260, 150, 61, 26))
        self.label_33.setObjectName("label_33")
        self.tf_Laboratorio_nombre = QtWidgets.QLineEdit(self.tab_6)
        self.tf_Laboratorio_nombre.setGeometry(QtCore.QRect(350, 150, 158, 27))
        self.tf_Laboratorio_nombre.setObjectName("tf_Laboratorio_nombre")
        self.bt_Laboratorio_agregar = QtWidgets.QPushButton(self.tab_6)
        self.bt_Laboratorio_agregar.setGeometry(QtCore.QRect(150, 240, 121, 41))
        self.bt_Laboratorio_agregar.setObjectName("bt_Laboratorio_agregar")
        self.bt_Laboratorio_cancelar = QtWidgets.QPushButton(self.tab_6)
        self.bt_Laboratorio_cancelar.setGeometry(QtCore.QRect(300, 320, 151, 41))
        self.bt_Laboratorio_cancelar.setObjectName("bt_Laboratorio_cancelar")
        self.bt_Laboratorio_Modificar = QtWidgets.QPushButton(self.tab_6)
        self.bt_Laboratorio_Modificar.setGeometry(QtCore.QRect(310, 240, 121, 41))
        self.bt_Laboratorio_Modificar.setObjectName("bt_Laboratorio_Modificar")
        self.bt_Laboratorio_Eliminar = QtWidgets.QPushButton(self.tab_6)
        self.bt_Laboratorio_Eliminar.setGeometry(QtCore.QRect(460, 240, 121, 41))
        self.bt_Laboratorio_Eliminar.setObjectName("bt_Laboratorio_Eliminar")
        self.bt_FindLaboratorio = QtWidgets.QPushButton(self.tab_6)
        self.bt_FindLaboratorio.setGeometry(QtCore.QRect(520, 110, 161, 27))
        self.bt_FindLaboratorio.setObjectName("bt_FindLaboratorio")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.label_31 = QtWidgets.QLabel(self.tab_7)
        self.label_31.setGeometry(QtCore.QRect(250, 50, 211, 31))
        self.label_31.setStyleSheet("font: italic 20pt \"URW Palladio L\";")
        self.label_31.setObjectName("label_31")
        self.tf_Laboratorio_IdProduct = QtWidgets.QLineEdit(self.tab_7)
        self.tf_Laboratorio_IdProduct.setGeometry(QtCore.QRect(350, 130, 158, 27))
        self.tf_Laboratorio_IdProduct.setObjectName("tf_Laboratorio_IdProduct")
        self.label_32 = QtWidgets.QLabel(self.tab_7)
        self.label_32.setGeometry(QtCore.QRect(190, 130, 131, 26))
        self.label_32.setObjectName("label_32")
        self.tf_Laboratorio_cantidadProduct = QtWidgets.QLineEdit(self.tab_7)
        self.tf_Laboratorio_cantidadProduct.setGeometry(QtCore.QRect(350, 170, 158, 27))
        self.tf_Laboratorio_cantidadProduct.setObjectName("tf_Laboratorio_cantidadProduct")
        self.label_34 = QtWidgets.QLabel(self.tab_7)
        self.label_34.setGeometry(QtCore.QRect(190, 170, 131, 26))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.tab_7)
        self.label_35.setGeometry(QtCore.QRect(190, 210, 131, 26))
        self.label_35.setObjectName("label_35")
        self.tf_Laboratorio_costoVentaProducto = QtWidgets.QLineEdit(self.tab_7)
        self.tf_Laboratorio_costoVentaProducto.setGeometry(QtCore.QRect(350, 210, 158, 27))
        self.tf_Laboratorio_costoVentaProducto.setObjectName("tf_Laboratorio_costoVentaProducto")
        self.bt_Laboratorio_AgregarProducto = QtWidgets.QPushButton(self.tab_7)
        self.bt_Laboratorio_AgregarProducto.setGeometry(QtCore.QRect(540, 130, 151, 41))
        self.bt_Laboratorio_AgregarProducto.setObjectName("bt_Laboratorio_AgregarProducto")
        self.tb_lab_agregarproducto = QtWidgets.QTableWidget(self.tab_7)
        self.tb_lab_agregarproducto.setGeometry(QtCore.QRect(40, 280, 471, 241))
        self.tb_lab_agregarproducto.setObjectName("tb_lab_agregarproducto")
        self.tb_lab_agregarproducto.setColumnCount(0)
        self.tb_lab_agregarproducto.setRowCount(0)
        self.bt_loadprodlab = QtWidgets.QPushButton(self.tab_7)
        self.bt_loadprodlab.setGeometry(QtCore.QRect(530, 280, 97, 27))
        self.bt_loadprodlab.setObjectName("bt_loadprodlab")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tabPrincipal.addTab(self.tabCrudLaboratorios, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(280, 130, 20, 20))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(240, 180, 61, 20))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(220, 230, 71, 20))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(190, 280, 111, 20))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(190, 330, 111, 20))
        self.label_14.setObjectName("label_14")
        self.tf_Producto_id = QtWidgets.QLineEdit(self.tab)
        self.tf_Producto_id.setGeometry(QtCore.QRect(330, 130, 158, 27))
        self.tf_Producto_id.setObjectName("tf_Producto_id")
        self.tf_Producto_nombre = QtWidgets.QLineEdit(self.tab)
        self.tf_Producto_nombre.setGeometry(QtCore.QRect(330, 180, 158, 27))
        self.tf_Producto_nombre.setObjectName("tf_Producto_nombre")
        self.tf_Producto_Fabricante = QtWidgets.QLineEdit(self.tab)
        self.tf_Producto_Fabricante.setGeometry(QtCore.QRect(330, 230, 158, 27))
        self.tf_Producto_Fabricante.setObjectName("tf_Producto_Fabricante")
        self.tf_Producto_precioCoste = QtWidgets.QLineEdit(self.tab)
        self.tf_Producto_precioCoste.setGeometry(QtCore.QRect(330, 280, 158, 27))
        self.tf_Producto_precioCoste.setObjectName("tf_Producto_precioCoste")
        self.tf_Producto_PrecioVenta = QtWidgets.QLineEdit(self.tab)
        self.tf_Producto_PrecioVenta.setGeometry(QtCore.QRect(330, 330, 158, 27))
        self.tf_Producto_PrecioVenta.setObjectName("tf_Producto_PrecioVenta")
        self.label_29 = QtWidgets.QLabel(self.tab)
        self.label_29.setGeometry(QtCore.QRect(40, 530, 261, 20))
        self.label_29.setObjectName("label_29")
        self.label_26 = QtWidgets.QLabel(self.tab)
        self.label_26.setGeometry(QtCore.QRect(250, 40, 261, 31))
        self.label_26.setStyleSheet("font: italic 20pt \"URW Palladio L\";")
        self.label_26.setObjectName("label_26")
        self.bt_Producto_cancelar = QtWidgets.QPushButton(self.tab)
        self.bt_Producto_cancelar.setGeometry(QtCore.QRect(330, 670, 101, 41))
        self.bt_Producto_cancelar.setObjectName("bt_Producto_cancelar")
        self.bt_Producto_agregar = QtWidgets.QPushButton(self.tab)
        self.bt_Producto_agregar.setGeometry(QtCore.QRect(130, 590, 111, 41))
        self.bt_Producto_agregar.setObjectName("bt_Producto_agregar")
        self.cb_Producto_TieneProteccion = QtWidgets.QComboBox(self.tab)
        self.cb_Producto_TieneProteccion.setGeometry(QtCore.QRect(330, 530, 151, 27))
        self.cb_Producto_TieneProteccion.setObjectName("cb_Producto_TieneProteccion")
        self.cb_Producto_TieneProteccion.addItem("")
        self.cb_Producto_TieneProteccion.addItem("")
        self.tf_Producto_Categoria = QtWidgets.QLineEdit(self.tab)
        self.tf_Producto_Categoria.setGeometry(QtCore.QRect(330, 370, 158, 27))
        self.tf_Producto_Categoria.setObjectName("tf_Producto_Categoria")
        self.label_36 = QtWidgets.QLabel(self.tab)
        self.label_36.setGeometry(QtCore.QRect(230, 370, 71, 20))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.tab)
        self.label_37.setGeometry(QtCore.QRect(130, 440, 171, 20))
        self.label_37.setObjectName("label_37")
        self.tf_Producto_DescripcionProducto = QtWidgets.QPlainTextEdit(self.tab)
        self.tf_Producto_DescripcionProducto.setGeometry(QtCore.QRect(330, 440, 251, 75))
        self.tf_Producto_DescripcionProducto.setObjectName("tf_Producto_DescripcionProducto")
        self.bt_Producto_Modificar = QtWidgets.QPushButton(self.tab)
        self.bt_Producto_Modificar.setGeometry(QtCore.QRect(320, 590, 111, 41))
        self.bt_Producto_Modificar.setObjectName("bt_Producto_Modificar")
        self.bt_Producto_Eliminar = QtWidgets.QPushButton(self.tab)
        self.bt_Producto_Eliminar.setGeometry(QtCore.QRect(520, 590, 111, 41))
        self.bt_Producto_Eliminar.setObjectName("bt_Producto_Eliminar")
        self.bt_FindProducto = QtWidgets.QPushButton(self.tab)
        self.bt_FindProducto.setGeometry(QtCore.QRect(500, 130, 161, 27))
        self.bt_FindProducto.setObjectName("bt_FindProducto")
        self.label_76 = QtWidgets.QLabel(self.tab)
        self.label_76.setGeometry(QtCore.QRect(230, 410, 61, 20))
        self.label_76.setObjectName("label_76")
        self.tf_Producto_Cantidad = QtWidgets.QLineEdit(self.tab)
        self.tf_Producto_Cantidad.setGeometry(QtCore.QRect(330, 410, 158, 27))
        self.tf_Producto_Cantidad.setObjectName("tf_Producto_Cantidad")
        self.tabPrincipal.addTab(self.tab, "")

        self.retranslateUi(Dialog)
        self.tabPrincipal.setCurrentIndex(0)
        self.tb_agregarFarmacia.setCurrentIndex(1)
        self.tabPrincipal_2.setCurrentIndex(1)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Farmacias"))
        self.tabCrudFarmacias.setToolTip(_translate("Dialog", "<html><head/><body><p>uhyasvbfd</p></body></html>"))
        self.label_2.setText(_translate("Dialog", "Agregar Farmacia"))
        self.label_4.setText(_translate("Dialog", "Codigo de Farmacia"))
        self.bt_Farmacia_Cancelar.setText(_translate("Dialog", "Cancelar"))
        self.label_3.setText(_translate("Dialog", "Direccion Completa"))
        self.bt_Farmacia_asigPropietarios.setText(_translate("Dialog", "Asigar"))
        self.label_9.setText(_translate("Dialog", "Asignar Farmaceuticos"))
        self.bt_Farmacia_Agregar.setText(_translate("Dialog", "Agregar"))
        self.bt_Farmacia_asigFarmaceuticos.setText(_translate("Dialog", "Asigar"))
        self.label_7.setText(_translate("Dialog", "Ciudad"))
        self.label_6.setText(_translate("Dialog", "Departamento"))
        self.label_8.setText(_translate("Dialog", "Calle"))
        self.label_5.setText(_translate("Dialog", "Asignar Propietarios"))
        self.bt_Farmacia_Modificar.setText(_translate("Dialog", "Modificar"))
        self.bt_Farmacia_Eliminar.setText(_translate("Dialog", "Eliminar"))
        self.bt_FindFarmacia.setText(_translate("Dialog", "Buscar Farmacia"))
        self.bt_load.setText(_translate("Dialog", "Load"))
        self.label_74.setText(_translate("Dialog", "Asignar Almacenes"))
        self.bt_asignaralmancen.setText(_translate("Dialog", "Asigar"))
        self.tb_agregarFarmacia.setTabText(self.tb_agregarFarmacia.indexOf(self.tab_4), _translate("Dialog", "Agregar Farmacia"))
        self.label_15.setText(_translate("Dialog", "Productos Disponibles"))
        self.label_27.setText(_translate("Dialog", "Codigo de Farmacia"))
        self.bt_Farmacia_BuscarProductos.setText(_translate("Dialog", "BUSCAR"))
        self.label_77.setText(_translate("Dialog", "Almacenes"))
        self.label_90.setText(_translate("Dialog", "Codigo Almacen"))
        self.bt_almacen_farmacia.setText(_translate("Dialog", "BUSCAR"))
        self.label_91.setText(_translate("Dialog", "Productos"))
        self.tb_agregarFarmacia.setTabText(self.tb_agregarFarmacia.indexOf(self.tab_5), _translate("Dialog", "Almacen de Farmacia"))
        self.tb_agregarFarmacia.setTabText(self.tb_agregarFarmacia.indexOf(self.tab_3), _translate("Dialog", "Compra a Laboratorios"))
        self.tabPrincipal.setTabText(self.tabPrincipal.indexOf(self.tabCrudFarmacias), _translate("Dialog", "Farmacias"))
        self.Almacenes.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Almaneces</p><p><br/></p></body></html>"))
        self.bt_agregarAlmacen.setText(_translate("Dialog", "Agregar"))
        self.label_75.setText(_translate("Dialog", "Codigo"))
        self.tabPrincipal.setTabText(self.tabPrincipal.indexOf(self.Almacenes), _translate("Dialog", "Almacenes"))
        self.label_16.setText(_translate("Dialog", "Nombre Completo"))
        self.label_17.setText(_translate("Dialog", "Agregar Farmaceuticos"))
        self.label_18.setText(_translate("Dialog", "Direccion"))
        self.label_19.setText(_translate("Dialog", "Edad"))
        self.label_20.setText(_translate("Dialog", "ID"))
        self.bt_Farmaceutico_cancelar.setText(_translate("Dialog", "Cancelar"))
        self.bt_Farmaceutico_agregar.setText(_translate("Dialog", "Agregar"))
        self.bt_Farmaceutico_Modificar.setText(_translate("Dialog", "Modificar"))
        self.bt_Farmaceutico_Eliminar.setText(_translate("Dialog", "Eliminar"))
        self.bt_FindFarmaceutico.setText(_translate("Dialog", "Buscar Farmaceutico"))
        self.tabCrudFarmacias_2.setToolTip(_translate("Dialog", "<html><head/><body><p>uhyasvbfd</p></body></html>"))
        self.label_38.setText(_translate("Dialog", "Agregar Farmacia"))
        self.label_39.setText(_translate("Dialog", "Codigo de Farmacia"))
        self.bt_Farmacia_Cancelar_2.setText(_translate("Dialog", "Cancelar"))
        self.label_40.setText(_translate("Dialog", "Direccion Completa"))
        self.bt_Farmacia_asigPropietarios_2.setText(_translate("Dialog", "Asigar"))
        self.label_41.setText(_translate("Dialog", "Asignar Farmaceuticos"))
        self.bt_Farmacia_Agregar_2.setText(_translate("Dialog", "Agregar"))
        self.bt_Farmacia_asigFarmaceuticos_2.setText(_translate("Dialog", "Asigar"))
        self.label_42.setText(_translate("Dialog", "Ciudad"))
        self.label_43.setText(_translate("Dialog", "Departamento"))
        self.label_44.setText(_translate("Dialog", "Calle"))
        self.label_45.setText(_translate("Dialog", "Asignar Propietarios"))
        self.bt_Farmacia_Modificar_2.setText(_translate("Dialog", "Modificar"))
        self.bt_Farmacia_Eliminar_2.setText(_translate("Dialog", "Eliminar"))
        self.bt_FindFarmacia_2.setText(_translate("Dialog", "Buscar Farmacia"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("Dialog", "Agregar Farmacia"))
        self.label_46.setText(_translate("Dialog", "Productos Disponibles"))
        self.label_47.setText(_translate("Dialog", "Codigo de Farmacia"))
        self.bt_Farmacia_BuscarProductos_2.setText(_translate("Dialog", "BUSCAR"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("Dialog", "Almacen de Farmacia"))
        self.tabPrincipal_2.setTabText(self.tabPrincipal_2.indexOf(self.tabCrudFarmacias_2), _translate("Dialog", "Farmacias"))
        self.label_48.setText(_translate("Dialog", "Nombre Completo"))
        self.label_49.setText(_translate("Dialog", "Agregar Farmaceuticos"))
        self.label_50.setText(_translate("Dialog", "Direccion"))
        self.label_51.setText(_translate("Dialog", "Edad"))
        self.label_52.setText(_translate("Dialog", "ID"))
        self.bt_Farmaceutico_cancelar_2.setText(_translate("Dialog", "Cancelar"))
        self.bt_Farmaceutico_agregar_2.setText(_translate("Dialog", "Agregar"))
        self.bt_Farmaceutico_Modificar_2.setText(_translate("Dialog", "Modificar"))
        self.bt_Farmaceutico_Eliminar_2.setText(_translate("Dialog", "Eliminar"))
        self.bt_FindFarmaceutico_2.setText(_translate("Dialog", "Buscar Farmaceutico"))
        self.tabPrincipal_2.setTabText(self.tabPrincipal_2.indexOf(self.tabCrudFarmaceuticos_2), _translate("Dialog", "Farmaceuticos"))
        self.label_53.setText(_translate("Dialog", "Agregar Propietarios"))
        self.label_54.setText(_translate("Dialog", "Nombre Completo"))
        self.label_55.setText(_translate("Dialog", "Edad"))
        self.label_56.setText(_translate("Dialog", "Direccion"))
        self.label_57.setText(_translate("Dialog", "ID"))
        self.bt_propietario_cancelar_2.setText(_translate("Dialog", "Cancelar"))
        self.bt_propietario_agregar_2.setText(_translate("Dialog", "Agregar"))
        self.bt_propietario_Modificar_2.setText(_translate("Dialog", "Modificar"))
        self.bt_propietario_Eliminar_2.setText(_translate("Dialog", "Eliminar"))
        self.bt_FindPropietario_2.setText(_translate("Dialog", "Buscar Propietario"))
        self.tabPrincipal_2.setTabText(self.tabPrincipal_2.indexOf(self.tabCrudPropietarios_2), _translate("Dialog", "Propietarios"))
        self.label_58.setText(_translate("Dialog", "Agregar Laboratorio"))
        self.label_59.setText(_translate("Dialog", "ID"))
        self.label_60.setText(_translate("Dialog", "Nombre"))
        self.bt_Laboratorio_agregar_2.setText(_translate("Dialog", "Agregar "))
        self.bt_Laboratorio_cancelar_2.setText(_translate("Dialog", "Cancelar"))
        self.bt_Laboratorio_Modificar_2.setText(_translate("Dialog", "Modificar"))
        self.bt_Laboratorio_Eliminar_2.setText(_translate("Dialog", "Eliminar"))
        self.bt_FindLaboratorio_2.setText(_translate("Dialog", "Buscar Laboratorio"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_10), _translate("Dialog", "Agregar Laboratorio"))
        self.label_61.setText(_translate("Dialog", "Agregar Productos"))
        self.label_62.setText(_translate("Dialog", "Id del Producto"))
        self.label_63.setText(_translate("Dialog", "Cantidad"))
        self.label_64.setText(_translate("Dialog", "Costo de Venta"))
        self.bt_Laboratorio_AgregarProducto_2.setText(_translate("Dialog", "Agregar productos"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_11), _translate("Dialog", "Agregar Producto en Laboratorio"))
        self.tabPrincipal_2.setTabText(self.tabPrincipal_2.indexOf(self.tabCrudLaboratorios_2), _translate("Dialog", "Laboratorios"))
        self.label_65.setText(_translate("Dialog", "Id"))
        self.label_66.setText(_translate("Dialog", "Nombre"))
        self.label_67.setText(_translate("Dialog", "Fabricante"))
        self.label_68.setText(_translate("Dialog", "Precio de Coste"))
        self.label_69.setText(_translate("Dialog", "Precio de Venta"))
        self.label_70.setText(_translate("Dialog", "¿Esta protegido por la seguridad social?"))
        self.label_71.setText(_translate("Dialog", "Agregar Productos"))
        self.bt_Producto_cancelar_2.setText(_translate("Dialog", "Cancelar"))
        self.bt_Producto_agregar_2.setText(_translate("Dialog", "Agregar"))
        self.cb_Producto_TieneProteccion_2.setItemText(0, _translate("Dialog", "SI"))
        self.cb_Producto_TieneProteccion_2.setItemText(1, _translate("Dialog", "NO"))
        self.label_72.setText(_translate("Dialog", "Categoria"))
        self.label_73.setText(_translate("Dialog", "Descripcion del Producto"))
        self.bt_Producto_Modificar_2.setText(_translate("Dialog", "Modificar"))
        self.bt_Producto_Eliminar_2.setText(_translate("Dialog", "Eliminar"))
        self.bt_FindProducto_2.setText(_translate("Dialog", "Buscar Producto"))
        self.tabPrincipal_2.setTabText(self.tabPrincipal_2.indexOf(self.tab_2), _translate("Dialog", "Productos"))
        self.tabPrincipal.setTabText(self.tabPrincipal.indexOf(self.tabCrudFarmaceuticos), _translate("Dialog", "Farmaceuticos"))
        self.label_21.setText(_translate("Dialog", "Agregar Propietarios"))
        self.label_22.setText(_translate("Dialog", "Nombre Completo"))
        self.label_24.setText(_translate("Dialog", "Edad"))
        self.label_25.setText(_translate("Dialog", "Direccion"))
        self.label_23.setText(_translate("Dialog", "ID"))
        self.bt_propietario_cancelar.setText(_translate("Dialog", "Cancelar"))
        self.bt_propietario_agregar.setText(_translate("Dialog", "Agregar"))
        self.bt_propietario_Modificar.setText(_translate("Dialog", "Modificar"))
        self.bt_propietario_Eliminar.setText(_translate("Dialog", "Eliminar"))
        self.bt_FindPropietario.setText(_translate("Dialog", "Buscar Propietario"))
        self.tabPrincipal.setTabText(self.tabPrincipal.indexOf(self.tabCrudPropietarios), _translate("Dialog", "Propietarios"))
        self.label_28.setText(_translate("Dialog", "Agregar Laboratorio"))
        self.label_30.setText(_translate("Dialog", "ID"))
        self.label_33.setText(_translate("Dialog", "Nombre"))
        self.bt_Laboratorio_agregar.setText(_translate("Dialog", "Agregar "))
        self.bt_Laboratorio_cancelar.setText(_translate("Dialog", "Cancelar"))
        self.bt_Laboratorio_Modificar.setText(_translate("Dialog", "Modificar"))
        self.bt_Laboratorio_Eliminar.setText(_translate("Dialog", "Eliminar"))
        self.bt_FindLaboratorio.setText(_translate("Dialog", "Buscar Laboratorio"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("Dialog", "Agregar Laboratorio"))
        self.label_31.setText(_translate("Dialog", "Agregar Productos"))
        self.label_32.setText(_translate("Dialog", "Id del Producto"))
        self.label_34.setText(_translate("Dialog", "Cantidad"))
        self.label_35.setText(_translate("Dialog", "Costo de Venta"))
        self.bt_Laboratorio_AgregarProducto.setText(_translate("Dialog", "Agregar productos"))
        self.bt_loadprodlab.setText(_translate("Dialog", "LOAD"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("Dialog", "Agregar Producto en Laboratorio"))
        self.tabPrincipal.setTabText(self.tabPrincipal.indexOf(self.tabCrudLaboratorios), _translate("Dialog", "Laboratorios"))
        self.label_10.setText(_translate("Dialog", "Id"))
        self.label_11.setText(_translate("Dialog", "Nombre"))
        self.label_12.setText(_translate("Dialog", "Fabricante"))
        self.label_13.setText(_translate("Dialog", "Precio de Coste"))
        self.label_14.setText(_translate("Dialog", "Precio de Venta"))
        self.label_29.setText(_translate("Dialog", "¿Esta protegido por la seguridad social?"))
        self.label_26.setText(_translate("Dialog", "Agregar Productos"))
        self.bt_Producto_cancelar.setText(_translate("Dialog", "Cancelar"))
        self.bt_Producto_agregar.setText(_translate("Dialog", "Agregar"))
        self.cb_Producto_TieneProteccion.setItemText(0, _translate("Dialog", "SI"))
        self.cb_Producto_TieneProteccion.setItemText(1, _translate("Dialog", "NO"))
        self.label_36.setText(_translate("Dialog", "Categoria"))
        self.label_37.setText(_translate("Dialog", "Descripcion del Producto"))
        self.bt_Producto_Modificar.setText(_translate("Dialog", "Modificar"))
        self.bt_Producto_Eliminar.setText(_translate("Dialog", "Eliminar"))
        self.bt_FindProducto.setText(_translate("Dialog", "Buscar Producto"))
        self.label_76.setText(_translate("Dialog", "Cantidad"))
        self.tabPrincipal.setTabText(self.tabPrincipal.indexOf(self.tab), _translate("Dialog", "Productos"))

